### ISSUE TITLE
Getting 404 error on validate.js

### ISSUE THREAD

**Issue by erotavlas** [SitePen/dmodel#8]
We are trying to use extensions/jsonSchema.js module but it is unable to locate 'json-schema/lib/validate' 
What is this? This javascript file does not appear anywhere in the latest release (dmodel 0.1.0) or on the latest commit on github.

Please advise how to resolve this, Thanks

**Comment by dylans** [comment]
@erotavlas to use json-schema, you'll need to include the devDependency of json-schema, as noted in the package.json at https://github.com/SitePen/dmodel/blob/master/package.json#L26  Please verify that this works for you and close the ticket, assuming it does.

Beyond that, there is ongoing progress to move the repo from json-schema to https://github.com/json-schema-org/ because the only admin for the json-schema repo has become unresponsive. There are tickets open on this in the json-schema-org repo. If you find that it's ready for us to move to the json-schema-org version, please create a PR to update the package.json if you have time!

**Comment by erotavlas** [comment]
Is this the correct repo?

https://github.com/kriszyp/json-schema/releases

I could only find releases up to 0.2.1, but the dependency in package.json refers to a version 0.2.2
